### ISSUE TITLE
enlarge

### ISSUE THREAD

**Issue by codepilot-test** [jeremywrnr/cp-evaluation#11]
[issue screenshot](http://www.git-sync.com/screenshot/uyCnuN72zABTXSoR4)
[live code here](http://www.git-sync.com/render/fNmEEZhSdxNnPjqnW)
html:
```html
<head>
  <title>my website</title>
</head>

<body>
  <h1>welcome!</h1>
  <p> showing the demo update in real time </p>
  <p> adding another paragrpah </p>
</body>

```
css:
```css
body {
    background: green;
}

h1 {
    font-size: 50px;
}

h2 {
}

```
js:
```js
console.log("Hello world");

$(document).ready(function() {
    console.log("rejoice - jquery is enabled!");
});

```
console log:
```
[1:17:32 PM] beginning console output...
[1:17:32 PM] Hello world
[1:17:32 PM] rejoice - jquery is enabled!
```
