### ISSUE TITLE
be more friendly

### ISSUE THREAD

**Issue by jeremywrnr** [jeremywrnr/cp-evaluation#15]
[issue screenshot](http://www.git-sync.com/screenshot/qGXf63p7yM3RfDeoH)
[live code here](http://www.git-sync.com/render/LWvSy4PBntoYJxF7q)
html:
```html
<head>
  <title>my website</title>
</head>

<body>
  <h1>welcome!</h1>
  <p> showing the demo update in real time </p>
  <p> adding another paragrpah </p>
</body>

```
css:
```css
body {
    background: cyan;
}

h1 {
    font-size: 50px;
}

h2 {
}

```
js:
```js
console.log("Hello world");

$(document).ready(function() {
    console.log("rejoice - jquery is enabled!");
});

```
console log:
```
[2:31:50 PM] beginning console output...
[2:31:50 PM] Hello world
[2:31:50 PM] rejoice - jquery is enabled!
```
